### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by henriquek3** [rodrigopedra/laravel-history-navigation#1]
Poderia descrever um caso de uso para eu saber como utilizar?

**Comment by rodrigopedra** [comment]
Olá @henriquek3 , desculpa pelo atraso (mais de 3 anos!) em te responder, eu não uso mais este pacote e acabei perdendo sua notificação.

Eu imagino que o caso de uso que você poderia estar procurando 3 anos atrás já esteja resolvido, mas eu atualizei o README explicando melhor a intenção deste pacote e como usá-lo.

Eu não recomendo a adoção deste pacote em novos projetos, mas queria te dar uma resposta mesmo depois de tanto tempo =)

Um abraço!
