### ISSUE TITLE
Login/Logout issue in v1.0

### ISSUE THREAD

**Issue by esadewater** [rodrigopedra/laravel-history-navigation#4]
After upgrading to v1.0 I got some crashes while logging in/out. I'm using Laravel 10 with Jetstream/Fortify Login-scaffolding.
```json
        "laravel/framework": "^10.0",
        "laravel/jetstream": "^3.0",
        "rodrigopedra/laravel-history-navigation": "^1.0",
```
The exact log is:
`RodrigoPedra\HistoryNavigation\HistoryNavigationServiceProvider::RodrigoPedra\HistoryNavigation\{closure}(): Argument #1 ($container) must be of type Illuminate\Contracts\Container\Container, Illuminate\Auth\Events\Logout given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 421`

This pointed me to `RodrigoPedra\HistoryNavigation\HistoryNavigationServiceProvider.php` ll. 61-67:
```php
        $events->listen(Login::class, function (Container $container) {
            $container->make(HistoryNavigationService::class)->clear()->persist();
        });

        $events->listen(Logout::class, static function (Container $container) {
            $container->make(HistoryNavigationService::class)->clear()->persist();
        });
```

Seems like it's not always a container passed to the closure, but in case of login/logout it's the event itself. One way to fix this would be to not rely on dependency injection:
```php
        $events->listen(Login::class, function () {
            app(HistoryNavigationService::class)->clear()->persist();
        });

        $events->listen(Logout::class, static function () {
            app(HistoryNavigationService::class)->clear()->persist();
        });
```

**Comment by rodrigopedra** [comment]
Thanks for the report! It is fixed on v1.0.1. Give sometime for composer to reflect the new version.
